ARG RUST_VERSION=1.92.0
FROM rust:1.92.0 AS builder

WORKDIR /app

ENV SQLX_OFFLINE=true
COPY .sqlx .sqlx/
COPY .cargo .cargo/


# Build the base library
COPY Cargo.lock Cargo.toml .
RUN sed -i 's/^members/# members/' Cargo.toml
# Build base library-cached
RUN mkdir src && echo "fn main() {}" > src/lib.rs && cargo build --release
COPY src src

# Build base library
RUN cargo build --release

WORKDIR /app
RUN mkdir api/
COPY api/Cargo.toml api/
COPY Cargo.toml .
# Make api the only member of the workspace
RUN sed -i 's/^members.*$/members = ["api"]/' Cargo.toml

# Build api cache
RUN mkdir api/src && echo "fn main() {}" > api/src/main.rs && cargo build -p api --release

# Build api
COPY api/src api/src
RUN cargo build -p api --release

FROM debian:trixie-slim AS runner
WORKDIR /app
COPY --from=builder /app/target/release .
COPY .env .
ENTRYPOINT ["/app/api"]
